[machine]
device_kind = "mps"

[training]
task="prediction"
batch_size = 32
gradient_accumulation_steps = 1
evaluation_interval = 1000
checkpoint_interval = 1000
benchmarking_interval = 10_000
maximum_steps = 1_000_000

[model]
context_window = [32]
predict_width = 2
base_sample_interval_minutes = 15
input_sample_intervals_minutes = [15]
output_sample_intervals_minutes = [15]
alignment = 1440
model = "ssm"

[model.loss]
loss = "nll"
alpha_clip = 0.1
mode = "masked"

[model.ssm]
kernel = "s4"
number_of_embeddings = 1024
number_of_layers = 9
patch_size = 8
number_of_gaussians = 4

[benchmarking]
eval_quantiles = [0.01, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95, 0.99]

[optimizer]
learning_rate = 3e-5
weight_decay = 0
gradient_clipping = 1

[io]
feature_order = ["measurements_cdb", "weather"]
output = "out/"
gap_skip_hours  = 1

[io.features.measurements_cdb]
location = "data/LianderPower/"
loader = "croissant"

[io.features.weather]
location = "data/LianderPower/"
loader = "croissant"
nearest_neighbor = true
n_features = 4
subset_features = [
    "temperature_2m",
    "wind_speed_100m",
    "shortwave_radiation",
    "direct_normal_irradiance"
]
